// This file was generated by prisma-effect-generator, do not edit manually.

import type { Effect } from "effect"
import type { Prisma } from "@prisma/client"
import type { PrismaError } from "./index.js"

export type EffectPrismaService = {
  $executeRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) => Effect.Effect<number, PrismaError>
  $executeRawUnsafe: (query: string, ...values: any[]) => Effect.Effect<number, PrismaError>
  $queryRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) => Effect.Effect<unknown, PrismaError>
  $queryRawUnsafe: (query: string, ...values: any[]) => Effect.Effect<unknown, PrismaError>
    user: {
    findMany: <T extends Prisma.UserFindManyArgs>(args?: T) => Effect.Effect<Array<Prisma.UserGetPayload<T>>, PrismaError>
    findUnique: <T extends Prisma.UserFindUniqueArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T> | null, PrismaError>
    findFirst: <T extends Prisma.UserFindFirstArgs>(args?: T) => Effect.Effect<Prisma.UserGetPayload<T> | null, PrismaError>
    findUniqueOrThrow: <T extends Prisma.UserFindUniqueOrThrowArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    findFirstOrThrow: <T extends Prisma.UserFindFirstOrThrowArgs>(args?: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    create: <T extends Prisma.UserCreateArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    createMany: (args: Prisma.UserCreateManyArgs) => Effect.Effect<Prisma.BatchPayload, PrismaError>
    createManyAndReturn: <T extends Prisma.UserCreateManyAndReturnArgs>(args: T) => Effect.Effect<Array<Prisma.UserGetPayload<T>>, PrismaError>
    update: <T extends Prisma.UserUpdateArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    updateMany: (args: Prisma.UserUpdateManyArgs) => Effect.Effect<Prisma.BatchPayload, PrismaError>
    upsert: <T extends Prisma.UserUpsertArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    delete: <T extends Prisma.UserDeleteArgs>(args: T) => Effect.Effect<Prisma.UserGetPayload<T>, PrismaError>
    deleteMany: (args?: Prisma.UserDeleteManyArgs) => Effect.Effect<Prisma.BatchPayload, PrismaError>
    count: (args?: Prisma.UserCountArgs) => Effect.Effect<number, PrismaError>
    aggregate: <T extends Prisma.UserAggregateArgs>(args: T) => Effect.Effect<Prisma.GetScalarType<T, Prisma.UserGetPayload<T>>, PrismaError>
    groupBy: <T extends Prisma.UserGroupByArgs>(args: T) => Effect.Effect<any, PrismaError> // Complexity of GroupBy types is high, falling back to any for now or basic checks
  }
}
